import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Inter, Mada } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const mada = Mada({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mada.className}>{children}</body>
    </html>
  );
}
